os: osx
language: generic
osx_image: xcode9.4
env:
  -PARENT="1BPIKK7sxbfdDu59wKmp3dl83lXpTkHRJ"
  -TOKEN="dnzg-ghsa-ctnp-eitj"
  -IPA_PATH="niuz.ipa"
before_script:
  # - export HOMEBREW_NO_AUTO_UPDATE=1
  - set -o pipefail
  - pip install six
  - brew update
  - brew install gdrive
  - brew install libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - git clone https://oauth2:${MY_ACCESS_TOKEN}@gitlab.com/anykao/niuz.git
  - git clone https://github.com/anykao/video_player
  - git clone https://github.com/anykao/chewie
script:
  - cd niuz
  - flutter -v build ios --no-codesign
  - mkdir -p Payload
  - mv build/ios/iphoneos/Runner.app Payload
  - zip -r ${IPA_PATH} Payload
  - ls -lh ${IPA_PATH}
after_script:
  - gdrive upload --refresh-token ${REFRESH_TOKEN} --parent ${PARENT} ${IPA_PATH}
cache:
  directories:
    - $HOME/.pub-cache
